### ISSUE TITLE
Sinytra Connector compatibility

### ISSUE THREAD

**Issue by Congumelin** [BareMinimumStudios/playerex#9]
make it compatible with cytra connector pls

**Comment by pokesmells** [comment]
We are currently prioritizing a huge rewrite so before we do anything regarding that, we need to finish that

**Comment by ToppyTopology** [comment]
hope to see this aswell

**Comment by bibi-reden** [comment]
Safe to say that PlayerEX **should** be compatible with connector from the latest alpha (12) and the latest data attributes. Though it probably requires some testing to 100% confirm.

**Comment by cassie-jfs** [comment]
use connector
